### ISSUE TITLE
Disabling some features in LethalThings

### ISSUE THREAD

**Issue by jemorg2316** [EvaisaDev/LethalLib#10]
Really like what you've done with the Lethal things mod, but some friends wanted to cut back on some of the things added to the mod. Is there anyway to remove some things, like the rocket launcher or the Boomba?

**Comment by EvaisaDev** [comment]
Just turn the weights to 0 in the config file.
Everyone needs to have the same config

**Comment by jemorg2316** [comment]
I know what file it is but, im not sure how to edit it while it is a .dll file. kinda new to coding and dont know alot atm

**Comment by jemorg2316** [comment]
nevermind, im stupid. figured it out
