### ISSUE TITLE
add a hook immediately before terminal update

### ISSUE THREAD

**Issue by hades** [EvaisaDev/LethalLib#12]
I'm writing a mod that adds an item based on existing objects in the game. I'd like to use your library, because it's quite convenient; however I find it difficult to hook into the game such that the existing objects from the base game are already loaded.

I'm thinking it would be convenient if I could ask LethalLib to run my code immediately before it interacts with Terminal, which would allow me to create all my items when all the needed objects are guaranteed to be available.

I'm also very new to modding Unity games, so perhaps I'm overthinking it, and there's already a nice place to patch in, that I don't know of? In which case I would be grateful for any pointers.

**Comment by EvaisaDev** [comment]
sadly that's not really doable in a way that won't break stuff, since it needs to do stuff immediately on init of some scripts.
I recommend just building your custom item entirely in unity, and loading it from bundle.
