### ISSUE TITLE
Duplicated Scrap, Fake scrap decoy or Scrap desync

### ISSUE THREAD

**Issue by DigitalIver** [EvaisaDev/LethalLib#14]
When a player pick up a scrap it leave an invisible scrap decoy that you can't pick it up and can sometime add weight to you for no reason, we also discuss about this issue on lethal expansion github one. Here a video: 

https://github.com/EvaisaDev/LethalLib/assets/153030687/6c37c01e-afc5-43f0-b120-e030a4efe6b1

site that i start discovered this issue: https://github.com/HolographicWings/LethalExpansion/issues/34

**Comment by EvaisaDev** [comment]
Must be something done wrong with that mod's asset setup or something, never seen this happen with my own mods

**Comment by IverDigital** [comment]
hmm ok
