### ISSUE TITLE
Wrong dependency; should be using BepInEx-BepInExPack

### ISSUE THREAD

**Issue by solidterre** [EvaisaDev/LethalLib#16]
You should be using the [BepInEx-BepInExPack](https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/) dependency but are using a deprecated one: bbepis-BepInExPack-5.4.2113

Could you resolve this and push a new 2.0.0 version please ? This is causing issues with other mods.

At this time your mod is unusable for some people :-)

Bad dependency:
![image](https://github.com/EvaisaDev/LethalLib/assets/8171049/3c34967d-b3aa-4c23-8f09-523b76d2477b)

**Comment by solidterre** [comment]
Same for LethalThings mod

**Comment by EvaisaDev** [comment]
I do not know what you are talking about, my mods already target the correct one.
![qjVfabunx](https://github.com/EvaisaDev/LethalLib/assets/27735599/de5fd4fd-e06b-4cb1-a12b-74411fefa740)
