### ISSUE TITLE
Missed opportunity to use BaseUnityPlugin.Info PluginInfo instead of GetCallingAssembly

### ISSUE THREAD

**Issue by xiaoxiao921** [EvaisaDev/LethalLib#2]
https://github.com/EvaisaDev/LethalLib/blob/main/LethalLib/Modules/Items.cs#L244-L273

![image](https://github.com/EvaisaDev/LethalLib/assets/837334/91c50c51-c682-4c4f-ba8e-187d9e2ccf7f)

**Comment by EvaisaDev** [comment]
That would only get the current plugin (LethalLib). GetCallingAssembly gets the assembly that called the function.
So if LethalThings adds an item it'll show LethalThings instead of LethalLib.

**Comment by Niconoko** [comment]
Is the LethalLib and LethalThings got the same stuff? *Maow* :3

**Comment by xiaoxiao921** [comment]
> That would only get the current plugin (LethalLib). GetCallingAssembly gets the assembly that called the function. So if LethalThings adds an item it'll show LethalThings instead of LethalLib.

the whole point is to link the items to an unique identifier, the mod that would add an item through your lib would always be uniquely identified because when they'd try to add an item through your lib they'd have to give their plugin info (guid)
