### ISSUE TITLE
Create Shop Items without actual assets

### ISSUE THREAD

**Issue by JaydenMaalouf** [EvaisaDev/LethalLib#21]
I'm trying to create a purchasable item that exists in the shop items menu but it doesn't actually need to be a physical item. It's more of a "modification"

Is there a way to register an item without referencing an asset bundle?

**Comment by EvaisaDev** [comment]
I have better tools for copying assets through code now, but it is still not recommended.

**Comment by JaydenMaalouf** [comment]
> I have better tools for copying assets through code now, but it is still not recommended.

Would you be able to provide an example of how I would go about that?

**Comment by Hamunii** [comment]
I don't know if you ever figured out a way, but registering an item without a prefab isn't a feature that's planned, and copying an existing asset should be possible already (although I don't have a solution for this), so I'm closing this.
