### ISSUE TITLE
Can't 'confirm' going to moons with LethalLib mods and LethalAutoComplete

### ISSUE THREAD

**Issue by Venaf** [EvaisaDev/LethalLib#25]
[Bug on LethalAutoComplete's tracker](https://github.com/IlyaChichkov/LethalAutocompleteMod/issues/8)

Basically, typing Confirm does nothing when using LethalAutoComplete and any mod in my list involving LethalLib.  If LethalLib is active without any dependents, it works fine.

Modpack is 018cebcc-dab2-7958-1b8a-07e34048b513 with lots of things currently disabled for testing.

Enabling any of LethalThings, MirrorDecor, or Lategame_Upgrades causes the bug.

Thanks for your time in looking at this.

**Comment by Hamunii** [comment]
From this: https://github.com/IlyaChichkov/LethalAutocompleteMod/issues/8#issuecomment-1901147582, it seems like LethalLib isn't a problem either, or that the issue was magically fixed in some game update.
