### ISSUE TITLE
0.11.0 Update Incompatible with Moon Mods

### ISSUE THREAD

**Issue by ShrekOgre69** [EvaisaDev/LethalLib#27]
Updating LethalLib to 0.11.0 makes it so that any moon mods do not show up in the ship terminal, they are blank and the name only shows up if you try to route the ship to the moon if you know the name. LethalLib 0.10.4 works perfectly fine, it is only 0.11.0 that this issue occurs.

**Comment by EvaisaDev** [comment]
do you have an example of a mod that causes this?

**Comment by ShrekOgre69** [comment]
Yes, for example the Secret Labs moon mod. It shows up blank on the terminal, but when I type in route to Secret Labs, it does say that Secret Labs will cost money, it just doesn't show up on the list of moons to initially route to. I believe I have a second moon mod that too shows up as a blank line.

**Comment by EvaisaDev** [comment]
this is unrelated to lethallib, install Lethal Expansion Core and it should fix it

**Comment by ShrekOgre69** [comment]
And so it did.
