### ISSUE TITLE
Terminal Screen Texts

### ISSUE THREAD

**Issue by Niconoko** [EvaisaDev/LethalLib#3]
The texts in the terminal pop-outside from the monitor, me using v0.3.0
![image](https://github.com/EvaisaDev/LethalLib/assets/24541618/9923a80e-0930-4c2d-b03a-4954a406354e)
EDIT - Nvm, it was from Game Master mod.

**Comment by Niconoko** [comment]
Now me have questions instead,
1. Those physical perks are individual, or one for everyone once purchased?
2. Me playing solo and me bought 2 light footed, the message show me have 2 light footed perks in the list, is that normal?
That's it for now, thx in adv. *Maow* :3

**Comment by Muki39** [comment]
> Now me have questions instead,
> 
>     1. Those physical perks are individual, or one for everyone once purchased?
> 
>     2. Me playing solo and me bought 2 light footed, the message show me have 2 light footed perks in the list, is that normal?
>        That's it for now, thx in adv. _Maow_ :3

sounds like not from this maker, think you're thinking of this one?
https://thunderstore.io/c/lethal-company/p/malco/Lategame_Upgrades/

Their github
https://github.com/Malcolm-Q/LC-LateGameUpgrades

**Comment by Niconoko** [comment]
Oh, my bad, might got mixed up on the browser, and thx. :3
