### ISSUE TITLE
The mod currently causes a faulty save start.

### ISSUE THREAD

**Issue by ihummingbird** [EvaisaDev/LethalLib#33]
I started the game with this mod and the game only launches the hud and not the map, with a continuous stream of errors in the cmd.
I don't know what the reason was but disabling the mod fixed it.
This is the thunderstore code for the other active mods
018cfea0-9b33-bc3f-8064-8c4e8f0eb3fa

**Comment by EvaisaDev** [comment]
If you make a bug report please include your log file because i cannot do anything with this.

**Comment by ihummingbird** [comment]
I'm sorry, at the time when the error occurred I did not know where the logs were stored, and the bug was fixed after that so...
Thanks for the great mod. 👌
