### ISSUE TITLE
New update causes spawn next to the ship

### ISSUE THREAD

**Issue by callmelukyn** [EvaisaDev/LethalLib#34]
New update causes wrong spawn location. Even if new world is created, it causes everyone to spawn NOT in the ship.
Thunderstore modpack : 018cda00-ca45-ca38-3448-bebfedd8ff4f

**Comment by EvaisaDev** [comment]
Probably fixed in the latest update but next time you make a bug report please include a log

**Comment by Hamunii** [comment]
I don't know what this is about, but I'm assuming it was fixed so I'm closing since there isn't much to this
