### ISSUE TITLE
Calling Dungeon.AddDungeon() multiple times for the same dungeon flow causes bugs

### ISSUE THREAD

**Issue by Garcia2277** [EvaisaDev/LethalLib#37]
For the same dungeon flow, I am trying to add it to different moons with different weights using the following code:
```cs
Dungeon.AddDungeon(Assets.dungeon, 300, Levels.LevelTypes.DineLevel, null);
Dungeon.AddDungeon(Assets.dungeon, 300, Levels.LevelTypes.RendLevel, null);
Dungeon.AddDungeon(Assets.dungeon, 69, Levels.LevelTypes.TitanLevel, null);
```
However, one moon will get the proper dungeon index and the others will get -1 index. As you can imagine, the game fails when it loads the -1 dungeon index. Can the API be updated for this use case?

**Comment by EvaisaDev** [comment]
Will look into it

**Comment by Hamunii** [comment]
This functionality is now deprecated, LethalLevelLoader should be used for dungeons instead.
