### ISSUE TITLE
Unable to use ESC or Tab and no credits

### ISSUE THREAD

**Issue by XarianK** [EvaisaDev/LethalLib#38]
I'm unsure whats causing it directly, however whenever i have this mod enabled  it seems to cause any save (including new ones) to start with 0 credits as well as making me unable to bring up the pause menu or escape the Terminal. When stuck in the terminal it doesnt seem like any command works and instead causes me to be able to text above the actual screen and in between the pre-generated text (such as in between the store options).

**Comment by SyndicatMeow** [comment]
Same Issue here, however even past versions tested down to 11.2 appear to be having this issue. this could likely be in compatibility with the game, or a conflict between mods. it requires more testing I guess. Hope what I wrote helps.

Edit:  here is the log of my main and testing profiles
Main:
[LogOutput.log](https://github.com/EvaisaDev/LethalLib/files/13982897/LogOutput.log)
Test 1:
[LogOutput.log](https://github.com/EvaisaDev/LethalLib/files/13982902/LogOutput.log)
Last Test (literally only added the fumo mod that relied on this):
[LogOutput.log](https://github.com/EvaisaDev/LethalLib/files/13982903/LogOutput.log)

**Comment by SyndicatMeow** [comment]
### UPDATE

after a while of verifying files  and writing that report yesterday and the logs. it turns out every issue was fixed upon the game finally becoming v49 instead of v45, thus I like to retract my issue. but will leave this for the future.
