### ISSUE TITLE
Lethal Lib can't load modded shop items.

### ISSUE THREAD

**Issue by Dixoul** [EvaisaDev/LethalLib#39]
When typing store I can't see Shells (mod for buying shotgun shells) or the items from LateGame Upgrades (Peeper, Night vision, etc).
Seems like Store API isn't working properly
I checked many times and my mods/librarys are up to date. Is the problem here or where?

**Comment by EvaisaDev** [comment]
please attach your bepinex log when you make a bug report because this does not help me find the source.

**Comment by Dixoul** [comment]
Hello. I Figured it out yesterday with LGU's guys. I just didn't add the MHOOK to the patchers folders. (dumb move by my part)

For now I just want to say that. Now when trying to download LethalLib 0.13.0, windows defender shows up and marks it as virus.
