### ISSUE TITLE
Missing items when log back in game / Dolls acting weird in the inventory

### ISSUE THREAD

**Issue by Niconoko** [EvaisaDev/LethalLib#4]
Some bought items seem to be disappear when log back into the game, like utility belt and rocket launcher. Not sure if other thing would be too.

Add - Forget to mention that some dolls when pick up, it make inventory gone weird and sometime can't interact with anything. Me think it's the small cat looking one if me recalled, not sure with the other one. So far, the green glasses one and the glowy eyes yoda one are fine.

**Comment by Zewo70** [comment]
got the same, both with dropping on the ground before logging off and keeping it in the inventory.

**Comment by EvaisaDev** [comment]
well the saving thing is fixed, the inventory thing is not something i can reproduce
