### ISSUE TITLE
Terminal Bug

### ISSUE THREAD

**Issue by BraDistrutta** [EvaisaDev/LethalLib#43]
I'm having a problem where the terminal is bugged, it shows no items and i can't exit from it, and in the log at lines 668-669 it displays this:
`[Info   : LethalLib] Adding 0 unlockables to unlockables list `
`[Info   : LethalLib] Adding 0 items to terminal `

It's probably some conflicting mods but i can't find which one is the problem

Here is the full log
[LogOutput.log](https://github.com/EvaisaDev/LethalLib/files/13931947/LogOutput.log)

**Comment by AnotherCrab1** [comment]
you can try downloading terminal mod with leave command im gonna try this rn

**Comment by AnotherCrab1** [comment]
uhh i was getting this error in past but rn i dont have it you gotta try it

**Comment by AnotherCrab1** [comment]
btw better download darmuhs terminal stuff

**Comment by Hamunii** [comment]
I have never heard of this issue, and since this is a somewhat old issue by now, so it's possible that this has been fixed somewhere.

But yeah since I've not heard of this being a thing in a long time, I'm assuming it's no longer a problem and closing this.
