### ISSUE TITLE
Items not being saved correctly

### ISSUE THREAD

**Issue by KingKalua808** [EvaisaDev/LethalLib#5]
Items are saved correctly when you save your save and load right back in. The problem occurs when you close your game fully. When you load back into your save, most of your items have changed into different things. Shotguns turned into portable radar and rocket launchers turned into maxwell scrap.

**Comment by EvaisaDev** [comment]
This depends on load order of mods, if anything changed in terms of mods your save games will break.
The game uses Indexing to find items. so item indexes will change if anything adds new content of any kind.

**Comment by KingKalua808** [comment]
Alright, good to know. Thank You. I'll close this.
