### ISSUE TITLE
About the teleport mines

### ISSUE THREAD

**Issue by Paradox75831004** [EvaisaDev/LethalLib#50]
Is it possible to add a config - which would be responsible for enabling the destruction of mines - after teleportation. It’s just that over the entire time I’ve been using this mod, I’ve noticed that people are abusing the system with mines, constantly teleporting, saving things, and so on. And so once it happened - the teleport mine broke - you travel further (only if the problem with the monsters remains - because of which they teleported by stepping on the mine, then this will not be relevant)

**Comment by Hamunii** [comment]
I'm assuming this is talking about [Lethal Things](https://github.com/EvaisaDev/LethalThings)? That's a different mod.
