### ISSUE TITLE
Only host can see custom items in 0.14.0 

### ISSUE THREAD

**Issue by Uniteria** [EvaisaDev/LethalLib#56]
Hi, as mentioned above, only host can see modded items on the ground. Other player can not as of version 0.14.0. We had to switch back to 0.13.2 to make it work once again.

**Comment by JSChronicles** [comment]
Same thing here:
Host can see items from lategameupgrades but others cannot.
Wheelbarrow shows to host but not others and others cannot interact with it.

We have all wiped mod cache and only installed LGU on a brand new profile after deleting the other profiles and manually cleared folder caches for mods with a brand new mod list install via code. This did not alleviate the issue until we reverted back to the last version for release.

We did also test that others that hosted could see the items but then the non-hosts for that game could not see them.

**Comment by nephatrine** [comment]
FacilityMeltdown commands also only show up for host. Seems like a lot of mod-added things are not working for the other players now. Had to roll back to 0.13.2.

**Comment by gustovafing** [comment]
Same thing here

**Comment by EvaisaDev** [comment]
Should be fixed
