### ISSUE TITLE
Add .csproj/change .gitignore

### ISSUE THREAD

**Issue by legoandmars** [EvaisaDev/LethalLib#6]
The current .gitignore file is a Unity gitignore file, which strips .csproj files 

This makes it a bit of a task to build this project, since you have to generate your own .csproj file

I'd recommend switching to [VisualStudio.gitignore](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore) if possible, it's what I generally use for my mods

**Comment by EvaisaDev** [comment]
don e
