### ISSUE TITLE
Error upon starting up LethalLib

### ISSUE THREAD

**Issue by ReOp14** [EvaisaDev/LethalLib#61]
Hello, I'm new to modding Lethal Company and I'm hoping I can have some help. I see that in the BepInEx terminal, it prints me this error upon starting up the game:
```
[Error  : Unity Log] TypeLoadException: Could not load type of field 'LethalLib.Modules.Enemies+<>O:<0>__RegisterLevelEnemies' (0) due to: Could not load file or assembly 'MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
LethalLib.Plugin.Awake () (at <4eedb4dc36094adcb65137cf81f2803d>:IL_0098)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
```

My only mod installed is LethalLib, and this goes away when LethalLib is taken out of the plugins folder. I tried running the last three versions of LethalLib and the issue persists.

Any help would be appreciated!

**Comment by ReOp14** [comment]
I found a fix by installing https://thunderstore.io/c/lethal-company/p/Evaisa/HookGenPatcher/

**Comment by axi548** [comment]
dosn't work anyway
