### ISSUE TITLE
worst mod ever

### ISSUE THREAD

**Issue by AnotherCrab1** [EvaisaDev/LethalLib#62]
so this mod causes alot of bugs 
1.two handed items stuck in your hands forever even if you die
2.cant escape terminal
3.lags
4.THOUSANDS OF MODS USING THIS MOD
please fix these troubles i want to download custom dungeon mod

**Comment by manuelwaltschek** [comment]
This is github not a steam review page. Content like this should be banned.

**Comment by EvaisaDev** [comment]
None of the problems you described are caused solely by this mod, it is most definitely compatibility issues.
