### ISSUE TITLE
Can't close out of terminal once opened.

### ISSUE THREAD

**Issue by Biohazz** [EvaisaDev/LethalLib#7]
With this mod enabled I can't exit out of the terminal once I have opened it. Tab key seems to be unresponsive. Have tried rolling to older versions with same effects. I am using thunderstore. Thanks

**Comment by EvaisaDev** [comment]
no idea, not something i have experienced myself

**Comment by AvocadoVR** [comment]
> With this mod enabled I can't exit out of the terminal once I have opened it. Tab key seems to be unresponsive. Have tried rolling to older versions with same effects. I am using thunderstore. Thanks

I've had this issue. Are you patching anything in Terminal?

**Comment by EvaisaDev** [comment]
Can't reproduce, presume mod incompatibility.
