### ISSUE TITLE
LethalLib causes Old Birds entity to not spawn on v50

### ISSUE THREAD

**Issue by Nuzza** [EvaisaDev/LethalLib#72]
With LethalLib enabled:
![image](https://github.com/EvaisaDev/LethalLib/assets/29596317/26f4bbcf-e857-4070-8559-33b9ea60a0b2)

With LethalLib disabled:
![image](https://github.com/EvaisaDev/LethalLib/assets/29596317/374930c6-9fd8-4a1c-a598-6626aacccb47)

**Comment by Ccode-lang** [comment]
On my side it causes all entity spawning to fail on every map. I get null exception in the terminal in the roundmanager update which causes spawning not to happen. I only have lethallib and my sirenhead mod installed

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoundManager.Update () (at <7c1294fdd4e74b13968c5a3e316e621a>:IL_004D)
```

**Comment by AidanTweedy** [comment]
I'm having the same exact issue, and can confirm that LethalLib seems to be the culprit here.

The first error message that pops up is a few seconds after pulling the lever to land the ship:
```
[Error  : Unity Log] Error while predicting outside enemies: System.NullReferenceException: Object reference not set to an instance of an object
  at RoundManager.PredictAllOutsideEnemies () [0x0004b] in <7c1294fdd4e74b13968c5a3e316e621a>:IL_004B
  at RoundManager.FinishGeneratingNewLevelClientRpc () [0x00135] in <7c1294fdd4e74b13968c5a3e316e621a>:IL_0135
```

... which is followed by the error @Ccode-lang mentioned, multiple times a second.

**Comment by Alex052195** [comment]
I am having the same issue of having no enemies spawn when LethalLib is enabled

**Comment by CoolLKKPS** [comment]
+1 need to fix like rn maybe

**Comment by Denlrt** [comment]
Такая же проблема , после добавления этого мода пропали все монстры? Ещё фикс не делали?

**Comment by Ccode-lang** [comment]
For me, this has been fixed. Haven't had any problems. I haven't specifically checked for old birds though.

**Comment by CoolLKKPS** [comment]
checked this issue are fixed
