### ISSUE TITLE
cant go to company building v.50

### ISSUE THREAD

**Issue by W1ngbroman** [EvaisaDev/LethalLib#78]
im trying to go to company building to sell but the problem is when i type it and press enter it doesn't work it does anyone now a work around? otherwise i would love for this to be fixes!

**Comment by Urbokie** [comment]
got the same problem, i hope it's gonna be fix

**Comment by Urbokie** [comment]
so if you want there is a mod name AutoCompanyBuilding which automaticaly route your ship on the company building on days 0

**Comment by W1ngbroman** [comment]
> so if you want there is a mod name AutoCompanyBuilding which automaticaly route your ship on the company building on days 0

I actually did find that mod but thank you. This seems to be the only fix rn so download this mod

**Comment by W1ngbroman** [comment]
Just download AutoCompanybuilding mod
