### ISSUE TITLE
-wasn't sure where to put this so figured issue would be best-

### ISSUE THREAD

**Issue by Elyriand21** [EvaisaDev/LethalLib#79]
Hi! I'm one of the co-authors of [Lethal Company Mod Library](https://github.com/Lillious/Lethal-Company-Mod-Library) and wanted to let you know that I love what you've done! The API for custom items, terminal keywords, and more is truly a beautiful thing.

I wanted to share the library we created in hopes that some of it would be useful for you and your collaborators! We're looking to keep things updated so I would love to have a conversation about how we could assist in your project so that there's not 100 different libraries out there for Lethal Company Modding.

Please keep up the good work! Look forward to hearing from you soon <3

**Comment by Hamunii** [comment]
I think it's best to not increase the amount of LethalLib's dependencies when it isn't strictly needed, and I don't think LethalLib would benefit from using your library, looking at what it does (being mostly utility wrapper methods), and considering what LethalLib does. LethalLib is also in maintenance mode pretty much, so not much will change with this Library
