### ISSUE TITLE
Failed to route to the company

### ISSUE THREAD

**Issue by LaonLee** [EvaisaDev/LethalLib#80]
[Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
[Info   : Unity Log] Parsed word: comp
[Info   : Unity Log] noun keyword: company ; verb keyword: route ; result null? : False
[Info   : Unity Log] result: CompanyMoonroute
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
LethalLevelLoader.TerminalManager.LockedNodeEventTest (TerminalNode& currentNode, TerminalNode& loadNode) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_0006)
LethalLevelLoader.TerminalManager.OnBeforeLoadNewNode (TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_004D)
LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_001B)
(wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
Terminal.OnSubmit () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_00FB)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update().

![屏幕截图 2024-05-04 163509](https://github.com/EvaisaDev/LethalLib/assets/168900261/572515c3-be26-48ca-8f26-ff530a14d1c9)

**Comment by cowev** [comment]
Also experiencing this

**Comment by abelgraux** [comment]
I have the same problem

**Comment by Hamunii** [comment]
I'm pretty sure this was an issue with LethalLevelLoader
