### ISSUE TITLE
Conflicts? An error has occurred

### ISSUE THREAD

**Issue by liliarowan** [EvaisaDev/LethalLib#86]
![error](https://github.com/EvaisaDev/LethalLib/assets/126414247/819318be-44c4-4343-870d-bfe3b7fa23d7)
this shows when i load LC while having any custom moon mod (and its respective dependencies) enabled.
Then, when my friends go to join, it wont let them and it says "an error has occurred"
any fix?

**Comment by UsefAyman** [comment]
any soloution yet? have the same problem

**Comment by Hamunii** [comment]
Was the mods installed with a mod manager? If not, this is likely user-error and you didn't install LethalLib (which, this is why a log would be important so we could confirm this).

BepInEx gives that error if a mod that is a dependency of a mod hasn't been loaded by BepInEx.

Under this assumption, I'm closing this.
