### ISSUE TITLE
Sound volume of Hacking Tool too loud/annoying?

### ISSUE THREAD

**Issue by haifrosch** [EvaisaDev/LethalLib#9]
My friends have expressed that the beeping noise the hacking tool does is way too loud for both the user, and the other players around it. The hacking tool can even be even heard from super far away apparently.

Is this a game balance decision to make it more risky to use it? If not I would suggest to either lower the volume, make the volume adjustable or make it less "annoying".

**Comment by EvaisaDev** [comment]
I don't know why it would be loud, the volume should be roughly the same as other items.
It has never seemed that loud to me :/

**Comment by EvaisaDev** [comment]
Added volume config file to LethalThings
