### ISSUE TITLE
Stuck On Landing On Moon

### ISSUE THREAD

**Issue by Kuroo2021** [EvaisaDev/LethalLib#90]
After pulling the switch the game get caught on loading a random seed and just sit there. There seems to be a bug, I disable LithalLib and it works after doing so. 

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HDLethalCompany.Patch.GraphicsPatch.SetFogQuality () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_003D)
HDLethalCompany.Patch.GraphicsPatch.RoundPostFix () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_0001)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?720313506(RoundManager)
LethalLib.Modules.Dungeon.RoundManager_GenerateNewFloor (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <64fae9f52f324ab2a8065723b0759a64>:IL_010B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?-1717732140(RoundManager)
RoundManager.GenerateNewLevelClientRpc (System.Int32 randomSeed, System.Int32 levelID, System.Int32 moldIterations, System.Int32 moldStartPosition, System.Int32[] syncDestroyedMold) (at <0b5b829887344817a21214132ea92eef>:IL_0268)
RoundManager.__rpc_handler_3073943002 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <0b5b829887344817a21214132ea92eef>:IL_00A7)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
RoundManager:GenerateNewLevelClientRpc(Int32, Int32, Int32, Int32, Int32[])
<LoadNewLevelWait>d__125:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HDLethalCompany.Patch.GraphicsPatch.SetFogQuality () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_003D)
HDLethalCompany.Patch.GraphicsPatch.RoundPostFix () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_0001)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?720313506(RoundManager)
LethalLib.Modules.Dungeon.RoundManager_GenerateNewFloor (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <64fae9f52f324ab2a8065723b0759a64>:IL_010B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?-1717732140(RoundManager)
RoundManager.GenerateNewLevelClientRpc (System.Int32 randomSeed, System.Int32 levelID, System.Int32 moldIterations, System.Int32 moldStartPosition, System.Int32[] syncDestroyedMold) (at <0b5b829887344817a21214132ea92eef>:IL_0268)
RoundManager+<LoadNewLevelWait>d__125.MoveNext () (at <0b5b829887344817a21214132ea92eef>:IL_0244)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

**Comment by Hamunii** [comment]
Looks like the error happens in HDLethalCompany's code, so could be that HDLethalCompany doesn't properly handle a thing LethalLib does.

So, please report this issue to the HDLethalCompany developer if you wish this to be fixed, as its method `HDLethalCompany.Patch.GraphicsPatch.SetFogQuality` is what didn't handle a NullReferenceException here.
